package com.example.weatherapp.domin.model

import com.google.gson.annotations.SerializedName

data class WeatherDetail(
    @SerializedName("app_max_temp") val appMaxTemp: Double,
    @SerializedName("app_min_temp") val appMinTemp: Double,
    @SerializedName("clouds") val clouds: Int,
    @SerializedName("clouds_hi") val cloudsHi: Int,
    @SerializedName("clouds_low") val cloudsLow: Int,
    @SerializedName("clouds_mid") val cloudsMid: Int,
    @SerializedName("datetime") val datetime: String,
    @SerializedName("dewpt") val dewpt: Double,
    @SerializedName("high_temp") val highTemp: Double,
    @SerializedName("low_temp") val lowTemp: Double,
    @SerializedName("max_dhi") val maxDhi: Double?,
    @SerializedName("max_temp") val maxTemp: Double,
    @SerializedName("min_temp") val minTemp: Double,
    @SerializedName("moon_phase") val moonPhase: Double,
    @SerializedName("moon_phase_lunation") val moonPhaseLunation: Double,
    @SerializedName("moonrise_ts") val moonriseTimestamp: Long,
    @SerializedName("moonset_ts") val moonsetTimestamp: Long,
    @SerializedName("ozone") val ozone: Double,
    @SerializedName("pop") val pop: Int,
    @SerializedName("precip") val precip: Double,
    @SerializedName("pres") val pres: Double,
    @SerializedName("rh") val relativeHumidity: Int,
    @SerializedName("slp") val seaLevelPressure: Double,
    @SerializedName("snow") val snow: Double,
    @SerializedName("snow_depth") val snowDepth: Double,
    @SerializedName("sunrise_ts") val sunriseTimestamp: Long,
    @SerializedName("sunset_ts") val sunsetTimestamp: Long,
    @SerializedName("temp") val temp: Double,
    @SerializedName("ts") val timestamp: Long,
    @SerializedName("uv") val uv: Double,
    @SerializedName("valid_date") val validDate: String,
    @SerializedName("vis") val visibility: Double,
    @SerializedName("weather") val weather: WeatherCondition,
    @SerializedName("wind_cdir") val windDirection: String,
    @SerializedName("wind_cdir_full") val windDirectionFull: String,
    @SerializedName("wind_dir") val windDirectionDegrees: Int,
    @SerializedName("wind_gust_spd") val windGustSpeed: Double,
    @SerializedName("wind_spd") val windSpeed: Double
)
